name: PF2E Expanded Summoner Release

on:
  workflow_dispatch:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Update Manifest
        run: |
          SYSTEM_VERSION=$(grep -oP '(?<="version": ")[^"]+' dist/module.json | tr -d '\n')
          echo "systemVersion=$SYSTEM_VERSION" >> $GITHUB_ENV
      - name: Zip Files
        working-directory: ./dist
        run: zip -r ./pf2e-expanded-summoner.zip ./*

      - name: Create Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.systemVersion }}
          allowUpdates: false
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dist/module.json,./dist/pf2e-expanded-summoner.zip"
          tag: ${{ env.systemVersion }}